name: CLI Tests

# Controls when the workflow will run
on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cli_tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4 
        with:
          python-version: 3.11

      - name: Install and Configure poetry
        run: |
          python -m pip install poetry==1.3.2
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-cli-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: python -m poetry install

      - name: Tests
        run: poetry run python -m pytest --disable-warnings -xv --cov

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          title: Code Coverage
          badge-title: Code Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          unique-id-for-comment: python3.11